<a href="https://colab.research.google.com/github/MarvinAntillon97/etl-data-pipeline/blob/main/etl_seguros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv

In [12]:
import pandas as pd

In [79]:
#Conectar con PostGresql
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_ad3f_user:dfCEzp79Czz4SFMCXmINhlJs1gBDNT9G@dpg-d6qu7s450q8c73bpf58g-a.oregon-postgres.render.com/etl_seguros_ad3f"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1

In [68]:
url_clientes = "https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/main/data/raw/clientes.csv"

clientes = pd.read_csv(url_clientes)

clientes.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [69]:
#Limpieza de datos
clientes = clientes.copy()

clientes.columns = clientes.columns.str.strip().str.lower()

for col in clientes.select_dtypes(include='object').columns:
    clientes[col] = clientes[col].astype(str).str.strip()

clientes = clientes.replace(r'^\s*$', pd.NA, regex=True)

In [70]:
# Email
clientes['email'] = clientes['email'].str.lower()

# Fecha
clientes['fecha_nacimiento'] = pd.to_datetime(
    clientes['fecha_nacimiento'], errors='coerce'
)

# Género
map_genero = {
    "hombre": "Masculino",
    "masculino": "Masculino",
    "m": "Masculino",
    "mujer": "Femenino",
    "femenino": "Femenino",
    "f": "Femenino"
}

clientes['genero'] = clientes['genero'].str.lower().map(map_genero)
clientes['genero'] = clientes['genero'].fillna("No especificado")

# Ciudad
map_ciudad = {
    "sanmiguel": "San Miguel",
    "s. miguel": "San Miguel",
    "san miguel": "San Miguel",
    "sta. ana": "Santa Ana",
    "sta ana": "Santa Ana",
    "santa ana": "Santa Ana",
    "ss": "San Salvador",
    "san salvador": "San Salvador"
}

clientes['ciudad'] = clientes['ciudad'].str.lower().replace(map_ciudad)
clientes['ciudad'] = clientes['ciudad'].str.title()

# Segmento
clientes['segmento'] = clientes['segmento'].fillna("No especificado")

# Quitar duplicados
clientes = clientes.drop_duplicates()

In [71]:
clientes.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Masculino,2011-11-24,San Miguel,nan
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,No especificado,NaT,Santa Ana,nan
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,NaT,San Miguel,nan
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,NaT,Lalibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,No especificado,1945-08-02,San Salvador,Pyme

In [72]:
clientes.isnull().sum()

id_cliente             0
nombre                 0
email                  0
genero                 0
fecha_nacimiento    2445
ciudad                 0
segmento               0
dtype: int64

In [73]:
clientes_validos = clientes[
    clientes['nombre'].notna() &
    clientes['email'].notna()
].copy()

clientes_rechazados = clientes[
    clientes['nombre'].isna() |
    clientes['email'].isna()
].copy()

In [74]:
def motivo(row):
    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['email']):
        motivos.append("email_vacio")

    return ",".join(motivos)

clientes_rechazados["motivo_rechazo"] = clientes_rechazados.apply(motivo, axis=1)

In [75]:
clientes_validos.to_csv("clientes_curated.csv", index=False)
clientes_rechazados.to_csv("clientes_rejects.csv", index=False)

In [78]:
pd.read_sql("SELECT * FROM clientes_rejects LIMIT 10", engine)

Empty DataFrame
Columns: [id_cliente, nombre, email, genero, fecha_nacimiento, ciudad, segmento, motivo_rechazo]
Index: []

BLOQUE DE ASEGURADORAS

In [14]:
url_aseguradoras = "https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/main/data/raw/aseguradoras.csv"

aseguradoras = pd.read_csv(url_aseguradoras)

aseguradoras.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [15]:
# Limpieza de datos aseguradoras

aseguradoras = aseguradoras.copy()

# Normalizar columnas
aseguradoras.columns = aseguradoras.columns.str.strip().str.lower()

# Limpiar espacios en texto
for col in aseguradoras.select_dtypes(include='object').columns:
    aseguradoras[col] = aseguradoras[col].astype(str).str.strip()

# Reemplazar vacíos por NaN
aseguradoras = aseguradoras.replace(r'^\s*$', pd.NA, regex=True)

# ==============================
# MEJORAS DE CALIDAD DE DATOS
# ==============================

# Limpiar nombres
aseguradoras['nombre'] = aseguradoras['nombre'].str.title()

# Limpiar país
aseguradoras['pais'] = aseguradoras['pais'].str.replace("ElSalvador", "El Salvador")
aseguradoras['pais'] = aseguradoras['pais'].str.title()

# Limpiar rating_riesgo
map_rating = {
    "alto": "Alto",
    "medio": "Medio",
    "bajo": "Bajo",
    "b": "Bajo"
}

aseguradoras['rating_riesgo'] = aseguradoras['rating_riesgo'].str.lower().map(map_rating)

aseguradoras['rating_riesgo'] = aseguradoras['rating_riesgo'].fillna("No especificado")

In [16]:
aseguradoras.head()

   id_aseguradora         nombre         pais    rating_riesgo
0               1  Aseguradora 1   Costa Rica             Alto
1               2  Aseguradora 2  El Salvador             Bajo
2               3  Aseguradora 3  El Salvador  No especificado
3               4  Aseguradora 4   Costa Rica            Medio
4               5  Aseguradora 5  El Salvador             Bajo

In [17]:
aseguradoras.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            15 non-null     object
 3   rating_riesgo   15 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

In [18]:
aseguradoras.isnull().sum()

id_aseguradora    0
nombre            0
pais              0
rating_riesgo     0
dtype: int64

In [19]:
# Separar datos aseguradoras

aseguradoras_validos = aseguradoras.copy()

In [20]:
# Crear rejects vacío (misma estructura)

aseguradoras_rechazados = aseguradoras[0:0]

# Exportar archivos

aseguradoras_validos.to_csv("aseguradoras_curated.csv", index=False)
aseguradoras_rechazados.to_csv("aseguradoras_rejects.csv", index=False)

In [21]:
# Subir a base de datos

aseguradoras_validos.to_sql(
    'aseguradoras_curated',
    engine,
    if_exists='append',
    index=False
)

aseguradoras_rechazados.to_sql(
    'aseguradoras_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [22]:
pd.read_sql("SELECT * FROM aseguradoras_curated LIMIT 5", engine)

   id_aseguradora         nombre         pais    rating_riesgo
0               1  Aseguradora 1   Costa Rica             Alto
1               2  Aseguradora 2  El Salvador             Bajo
2               3  Aseguradora 3  El Salvador  No especificado
3               4  Aseguradora 4   Costa Rica            Medio
4               5  Aseguradora 5  El Salvador             Bajo

BLOQUE CORREDORES

In [23]:
# ==============================
# CORREDORES
# ==============================

url_corredores = "https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/main/data/raw/corredores.csv"

corredores = pd.read_csv(url_corredores)

corredores.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [24]:
# Limpieza básica corredores

corredores = corredores.copy()

# Normalizar columnas
corredores.columns = corredores.columns.str.strip().str.lower()

# Limpiar espacios
for col in corredores.select_dtypes(include='object').columns:
    corredores[col] = corredores[col].astype(str).str.strip()

# Reemplazar vacíos por NaN
corredores = corredores.replace(r'^\s*$', pd.NA, regex=True)

In [25]:
# Mejoras de calidad

# Nombre
corredores['nombre'] = corredores['nombre'].str.title()

# Zona (aquí tienes nulos)
corredores['zona'] = corredores['zona'].str.title()
corredores['zona'] = corredores['zona'].fillna("No especificado")

# Nivel (CLAVE)
map_nivel = {
    "junior": "Junior",
    "mid": "Mid",
    "senior": "Senior"
}

corredores['nivel'] = corredores['nivel'].str.lower().map(map_nivel)
corredores['nivel'] = corredores['nivel'].fillna("No especificado")

# Años de experiencia
corredores['anios_experiencia'] = pd.to_numeric(
    corredores['anios_experiencia'], errors='coerce'
)

In [26]:
corredores.head()

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  Paracentral     Mid                4.0
1            2    José Ortiz García       Centro  Junior                0.0
2            3   María Ramírez Cruz       Centro  Senior                6.0
3            4  Fernanda Rojas Cruz          Nan  Senior                8.0
4            5      Ana Gómez Rojas          Nan  Senior                4.0

In [27]:
corredores.isnull().sum()

id_corredor          0
nombre               0
zona                 0
nivel                0
anios_experiencia    4
dtype: int64

In [28]:
# Separar datos válidos y rechazados

corredores_validos = corredores[
    corredores['anios_experiencia'].notna()
].copy()

corredores_rechazados = corredores[
    corredores['anios_experiencia'].isna()
].copy()

In [29]:
# Motivo de rechazo

def motivo(row):
    motivos = []

    if pd.isna(row['anios_experiencia']):
        motivos.append("experiencia_vacia")

    return ",".join(motivos)

corredores_rechazados["motivo_rechazo"] = corredores_rechazados.apply(motivo, axis=1)

In [30]:
corredores_validos.to_csv("corredores_curated.csv", index=False)
corredores_rechazados.to_csv("corredores_rejects.csv", index=False)

In [31]:
corredores_validos.to_sql(
    'corredores_curated',
    engine,
    if_exists='append',
    index=False
)

corredores_rechazados.to_sql(
    'corredores_rejects',
    engine,
    if_exists='append',
    index=False
)

4

In [32]:
pd.read_sql("SELECT * FROM corredores_rejects", engine)

,id_corredor,nombre,zona,nivel,anios_experiencia,motivo_rechazo
0,11,José Morales Flores,Nan,Junior,None,experiencia_vacia
1,15,Fernanda Cruz Reyes,Centro,Mid,None,experiencia_vacia
2,61,Carlos Torres Mendoza,Centro,Junior,None,experiencia_vacia
3,77,Valeria Vásquez Mendoza,Centro,Junior,None,experiencia_vacia
4,11,José Morales Flores,Nan,Junior,None,experiencia_vacia
5,15,Fernanda Cruz Reyes,Centro,Mid,None,experiencia_vacia
6,61,Carlos Torres Mendoza,Centro,Junior,None,experiencia_vacia
7,77,Valeria Vásquez Mendoza,Centro,Junior,None,experiencia_vacia

BLOQUE TIPOS DE SEGUROS

In [34]:
url_tipos = "https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/main/data/raw/tipos_seguro.csv"

tipos_seguro = pd.read_csv(url_tipos)

tipos_seguro.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

In [35]:
# Limpieza básica

tipos_seguro = tipos_seguro.copy()

tipos_seguro.columns = tipos_seguro.columns.str.strip().str.lower()

for col in tipos_seguro.select_dtypes(include='object').columns:
    tipos_seguro[col] = tipos_seguro[col].astype(str).str.strip()

tipos_seguro = tipos_seguro.replace(r'^\s*$', pd.NA, regex=True)

In [36]:
# Normalizar texto

tipos_seguro['tipo'] = tipos_seguro['tipo'].str.title()
tipos_seguro['categoria'] = tipos_seguro['categoria'].str.title()

# Rellenar categoría vacía
tipos_seguro['categoria'] = tipos_seguro['categoria'].fillna("No especificado")

In [37]:
# Limpiar riesgo_base

def limpiar_numero(valor):
    if pd.isna(valor):
        return None

    valor = str(valor).strip()

    if valor in ["", "-", "None", "nan"]:
        return None

    valor = valor.replace(",", ".")

    try:
        return float(valor)
    except:
        return None

tipos_seguro['riesgo_base'] = tipos_seguro['riesgo_base'].apply(limpiar_numero)

In [38]:
tipos_seguro.head()

   id_tipo_seguro        tipo    categoria  riesgo_base
0               1        Pyme     Familiar          NaN
1               2  Industrial  Empresarial         4.68
2               3  Industrial     Familiar         5.10
3               4  Industrial     Personal          NaN
4               5        Auto  Empresarial         9.07

In [39]:
tipos_seguro.isnull().sum()

id_tipo_seguro    0
tipo              0
categoria         0
riesgo_base       3
dtype: int64

In [40]:
# Separar datos

tipos_validos = tipos_seguro[
    tipos_seguro['riesgo_base'].notna()
].copy()

tipos_rechazados = tipos_seguro[
    tipos_seguro['riesgo_base'].isna()
].copy()

In [41]:
# Motivo de rechazo

def motivo(row):
    motivos = []

    if pd.isna(row['riesgo_base']):
        motivos.append("riesgo_vacio")

    return ",".join(motivos)

tipos_rechazados["motivo_rechazo"] = tipos_rechazados.apply(motivo, axis=1)

In [42]:
tipos_validos.to_csv("tipos_seguro_curated.csv", index=False)
tipos_rechazados.to_csv("tipos_seguro_rejects.csv", index=False)

In [43]:
tipos_validos.to_sql(
    'tipos_seguro_curated',
    engine,
    if_exists='append',
    index=False
)

tipos_rechazados.to_sql(
    'tipos_seguro_rejects',
    engine,
    if_exists='append',
    index=False
)

3

In [44]:
pd.read_sql("SELECT * FROM tipos_seguro_rejects", engine)

   id_tipo_seguro        tipo categoria riesgo_base motivo_rechazo
0               1        Pyme  Familiar        None   riesgo_vacio
1               4  Industrial  Personal        None   riesgo_vacio
2              12    Agrícola       Nan        None   riesgo_vacio

BLOQUE POLIZAS

In [45]:
url_polizas = "https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/main/data/raw/polizas.csv"

polizas = pd.read_csv(url_polizas)

polizas.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [46]:
polizas = polizas.copy()

polizas.columns = polizas.columns.str.strip().str.lower()

for col in polizas.select_dtypes(include='object').columns:
    polizas[col] = polizas[col].astype(str).str.strip()

polizas = polizas.replace(r'^\s*$', pd.NA, regex=True)

In [47]:
polizas['fecha_emision'] = pd.to_datetime(
    polizas['fecha_emision'], errors='coerce'
)

In [48]:
def limpiar_numero(valor):
    if pd.isna(valor):
        return None

    valor = str(valor).strip()

    if valor in ["", "-", "None", "nan"]:
        return None

    if "," in valor and "." in valor:
        if valor.rfind(",") > valor.rfind("."):
            valor = valor.replace(".", "")
            valor = valor.replace(",", ".")
        else:
            valor = valor.replace(",", "")
    elif "," in valor:
        valor = valor.replace(",", ".")

    try:
        return float(valor)
    except:
        return None

polizas['prima'] = polizas['prima'].apply(limpiar_numero)
polizas['comision'] = polizas['comision'].apply(limpiar_numero)
polizas['monto_asegurado'] = polizas['monto_asegurado'].apply(limpiar_numero)

In [49]:
polizas.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaT,184,42,15,2,829.53,NaN,139253.11
1,2,2026-02-16,2408,35,11,12,NaN,12.22,27544.32
2,3,NaT,540,42,4,9,1611.53,92.05,173298.36
3,4,NaT,2821,40,10,5,1866.62,456.99,244461.27
4,5,NaT,945,23,9,11,NaN,324.08,123407.75

In [50]:
polizas.isnull().sum()

id_poliza              0
fecha_emision      20628
id_cliente             0
id_corredor            0
id_aseguradora         0
id_tipo_seguro         0
prima               5000
comision            5142
monto_asegurado     4971
dtype: int64

In [51]:
# Separar datos

polizas_validos = polizas[
    polizas['fecha_emision'].notna() &
    polizas['prima'].notna() &
    polizas['comision'].notna() &
    polizas['monto_asegurado'].notna()
].copy()

polizas_rechazados = polizas[
    polizas['fecha_emision'].isna() |
    polizas['prima'].isna() |
    polizas['comision'].isna() |
    polizas['monto_asegurado'].isna()
].copy()

In [52]:
def motivo(row):
    motivos = []

    if pd.isna(row['fecha_emision']):
        motivos.append("fecha_invalida")

    if pd.isna(row['prima']):
        motivos.append("prima_invalida")

    if pd.isna(row['comision']):
        motivos.append("comision_invalida")

    if pd.isna(row['monto_asegurado']):
        motivos.append("monto_invalido")

    return ",".join(motivos)

polizas_rechazados["motivo_rechazo"] = polizas_rechazados.apply(motivo, axis=1)

In [53]:
polizas_validos.to_csv("polizas_curated.csv", index=False)
polizas_rechazados.to_csv("polizas_rejects.csv", index=False)

In [54]:
polizas_validos.to_sql(
    'polizas_curated',
    engine,
    if_exists='append',
    index=False
)

polizas_rechazados.to_sql(
    'polizas_rejects',
    engine,
    if_exists='append',
    index=False
)

799

In [55]:
pd.read_sql("SELECT * FROM polizas_rejects LIMIT 10", engine)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado,motivo_rechazo
0,1,NaT,184,42,15,2,829.53,NaN,139253.11,"fecha_invalida,comision_invalida"
1,2,2026-02-16,2408,35,11,12,NaN,12.22,27544.32,prima_invalida
2,3,NaT,540,42,4,9,1611.53,92.05,173298.36,fecha_invalida
3,4,NaT,2821,40,10,5,1866.62,456.99,244461.27,fecha_invalida
4,5,NaT,945,23,9,11,NaN,324.08,123407.75,"fecha_invalida,prima_invalida"
5,6,NaT,1295,17,1,1,943.49,NaN,71968.43,"fecha_invalida,comision_invalida"
6,7,NaT,1254,25,11,4,1400.82,188.40,258202.93,fecha_invalida
7,8,NaT,887,77,3,8,1670.56,258.75,NaN,"fecha_invalida,monto_invalido"
8,9,NaT,1670,66,8,12,NaN,131.85,125804.84,"fecha_invalida,prima_invalida"
9,11,NaT,2590,25,8,4,NaN,NaN,NaN,"fecha_invalida,prima_invalida,comision_invalid..."

BLOQUE SINIESTROS

In [56]:
url_siniestros = "https://raw.githubusercontent.com/MarvinAntillon97/etl-data-pipeline/main/data/raw/siniestros.csv"

siniestros = pd.read_csv(url_siniestros)

siniestros.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [57]:
siniestros = siniestros.copy()

siniestros.columns = siniestros.columns.str.strip().str.lower()

for col in siniestros.select_dtypes(include='object').columns:
    siniestros[col] = siniestros[col].astype(str).str.strip()

siniestros = siniestros.replace(r'^\s*$', pd.NA, regex=True)

In [58]:
siniestros['fecha_siniestro'] = pd.to_datetime(
    siniestros['fecha_siniestro'], errors='coerce'
)

/tmp/ipykernel_14036/712057225.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  siniestros['fecha_siniestro'] = pd.to_datetime(

In [59]:
siniestros['monto_siniestro'] = siniestros['monto_siniestro'].apply(limpiar_numero)

In [60]:
map_estado = {
    "abierto": "Abierto",
    "cerrado": "Cerrado",
    "en proceso": "En Proceso",
    "pendiente": "Pendiente",
    "rechazado": "Rechazado"
}

siniestros['estado'] = siniestros['estado'].str.lower().map(map_estado)
siniestros['estado'] = siniestros['estado'].fillna("No especificado")

In [61]:
siniestros.head()

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16          2092.59    Abierto
1             2       2465             NaT          7076.25    Abierto
2             3      15785      2025-09-19           702.27    Cerrado
3             4      14299             NaT           274.63    Abierto
4             5      12908             NaT          9377.69  Rechazado

In [62]:
siniestros.isnull().sum()

id_siniestro          0
id_poliza             0
fecha_siniestro    3702
monto_siniestro     943
estado                0
dtype: int64

In [63]:
siniestros_validos = siniestros[
    siniestros['fecha_siniestro'].notna() &
    siniestros['monto_siniestro'].notna()
].copy()

siniestros_rechazados = siniestros[
    siniestros['fecha_siniestro'].isna() |
    siniestros['monto_siniestro'].isna()
].copy()

In [64]:
def motivo(row):
    motivos = []

    if pd.isna(row['fecha_siniestro']):
        motivos.append("fecha_invalida")

    if pd.isna(row['monto_siniestro']):
        motivos.append("monto_invalido")

    return ",".join(motivos)

siniestros_rechazados["motivo_rechazo"] = siniestros_rechazados.apply(motivo, axis=1)

In [65]:
siniestros_validos.to_csv("siniestros_curated.csv", index=False)
siniestros_rechazados.to_csv("siniestros_rejects.csv", index=False)

In [66]:
siniestros_validos.to_sql(
    'siniestros_curated',
    engine,
    if_exists='append',
    index=False
)

siniestros_rechazados.to_sql(
    'siniestros_rejects',
    engine,
    if_exists='append',
    index=False
)

881

In [67]:
pd.read_sql("SELECT * FROM siniestros_rejects LIMIT 10", engine)

,id_siniestro,id_poliza,fecha_siniestro,monto_siniestro,estado,motivo_rechazo
0,2,2465,None,7076.25,Abierto,fecha_invalida
1,4,14299,None,274.63,Abierto,fecha_invalida
2,5,12908,None,9377.69,Rechazado,fecha_invalida
3,6,5107,None,10535.74,No especificado,fecha_invalida
4,7,3379,None,10513.30,Abierto,fecha_invalida
5,9,18118,None,NaN,Cerrado,"fecha_invalida,monto_invalido"
6,10,19947,None,8801.03,Cerrado,fecha_invalida
7,11,6448,None,1619.38,Abierto,fecha_invalida
8,12,4096,None,NaN,Rechazado,"fecha_invalida,monto_invalido"
9,14,8260,None,NaN,No especificado,"fecha_invalida,monto_invalido"